### PR TITLE
Update recipe terraform

### PR DESCRIPTION
**Pull request by l3andro**
atlantis plan

### CODE REVIEW

**Comment by 4tlantisb0t** [comment]
**Plan Error**
```
GET https://api.github.com/repos/l3andro/terraform-atlantis/pulls/6/files?per_page=300: 404 Not Found []
```

**Comment by l3andro** [comment]
atlantis help

**Comment by 4tlantisb0t** [comment]
```cmake
atlantis
Terraform Pull Request Automation

Usage:
  atlantis <command> [options] -- [terraform options]

Examples:
  # run plan in the root directory passing the -target flag to terraform
  atlantis plan -d . -- -target=resource

  # apply all unapplied plans from this pull request
  atlantis apply

  # apply the plan for the root directory and staging workspace
  atlantis apply -d . -w staging

Commands:
  plan     Runs 'terraform plan' for the changes in this pull request.
           To plan a specific project, use the -d, -w and -p flags.
  apply    Runs 'terraform apply' on all unapplied plans from this pull request.
           To only apply a specific plan, use the -d, -w and -p flags.
  unlock   Removes all atlantis locks and discards all plans for this PR.
           To unlock a specific plan you can use the Atlantis UI.
  help     View help.

Flags:
  -h, --help   help for atlantis

Use "atlantis [command] --help" for more information about a command.
```

**Comment by l3andro** [comment]
atlantis plan

**Comment by 4tlantisb0t** [comment]
Ran Plan for dir: `.` workspace: `default`

**Plan Error**
<details><summary>Show Output</summary>

```
running "/usr/local/bin/terraform init -input=false -no-color -upgrade" in "/home/atlantis/.atlantis/repos/l3andro/terraform-atlantis/6/default": exit status 1

Initializing the backend...

Warning: Interpolation-only expressions are deprecated

  on main.tf line 87, in data "template_file" "user_data":
  87:   template = "${file("userdata")}"

Terraform 0.11 and earlier required all non-constant expressions to be
provided via interpolation syntax, but this pattern is now deprecated. To
silence this warning, remove the "${ sequence from the start and the }"
sequence from the end of this expression, leaving just the inner expression.

Template interpolation syntax is still used to construct strings from
expressions when the template includes multiple interpolation sequences or a
mixture of literal strings and interpolations. This deprecation applies only
to templates that consist entirely of a single interpolation sequence.

(and 7 more similar warnings elsewhere)


Error: Invalid legacy provider address

This configuration or its associated state refers to the unqualified provider
"aws".

You must complete the Terraform 0.13 upgrade process before upgrading to later
versions.


Error: Invalid legacy provider address

This configuration or its associated state refers to the unqualified provider
"template".

You must complete the Terraform 0.13 upgrade process before upgrading to later
versions.


```
</details>

**Comment by 4tlantisb0t** [comment]
Ran Plan for dir: `.` workspace: `default`

**Plan Error**
<details><summary>Show Output</summary>

```
running "/usr/local/bin/terraform init -input=false -no-color -upgrade" in "/home/atlantis/.atlantis/repos/l3andro/terraform-atlantis/6/default": exit status 1
There are some problems with the configuration, described below.

The Terraform configuration must be valid before initialization so that
Terraform can determine which modules and providers need to be installed.

Warning: Interpolation-only expressions are deprecated

  on main.tf line 93, in data "template_file" "user_data":
  93:   template = "${file("userdata")}"

Terraform 0.11 and earlier required all non-constant expressions to be
provided via interpolation syntax, but this pattern is now deprecated. To
silence this warning, remove the "${ sequence from the start and the }"
sequence from the end of this expression, leaving just the inner expression.

Template interpolation syntax is still used to construct strings from
expressions when the template includes multiple interpolation sequences or a
mixture of literal strings and interpolations. This deprecation applies only
to templates that consist entirely of a single interpolation sequence.

(and 7 more similar warnings elsewhere)


Error: Unsupported argument

  on main.tf line 6, in terraform:
   6:   version = required_version = "= 0.12.29"

An argument named "version" is not expected here.


Error: Missing newline after argument

  on main.tf line 6, in terraform:
   6:   version = required_version = "= 0.12.29"

An argument definition must end with a newline.


```
</details>

**Pull request closed without merging**
